SNOWFLAKE_CONFIG = {
    'USERNAME': 'ADD_YOUR_VALUE',
    'ACCOUNT': 'ADD_YOUR_VALUE',
    'WAREHOUSE': 'COMPUTE_WH',
    'DATABASE': 'INVOICES_DATABASE',
    'SCHEMA': 'PUBLIC',
    'KEY_PASSWORD': 'ADD_YOUR_VALUE'
} 
